Feature: Runs Filter
greatnonprofits-nfp/rapidpro pull request #185
Opened 2021-03-22 14:51 UTC by ihor-palii

Ticket: https://app.asana.com/0/1159876841343611/1199517123604341/f

2021-03-25 22:37 UTC, teehamaral requested changes

2021-03-25 22:37 UTC, teehamaral commented on temba/flows/models.py
> +                runs = runs.filter(created_on__gte=after)
Per Rob recommendation, we should change from `created_on` to `modified_on` for the before/after filter

2021-03-25 22:37 UTC, teehamaral commented on temba/flows/models.py
> +                runs = runs.filter(created_on__lte=before)
Per Rob recommendation, we should change from `created_on` to `modified_on` for the before/after filter

2021-03-25 22:37 UTC, teehamaral commented on temba/flows/views.py
> +                runs = runs.filter(created_on__gte=after)
Per Rob recommendation, we should change from `created_on` to `modified_on` for the before/after filter

2021-03-25 22:37 UTC, teehamaral commented on temba/flows/views.py
> +                runs = runs.filter(created_on__lte=before)
Per Rob recommendation, we should change from `created_on` to `modified_on` for the before/after filter

2021-03-29 11:06 UTC, ihor-palii commented
Updated

2021-03-29 14:11 UTC, teehamaral approved these changes

2021-03-30 00:34 UTC, merged