Feature: Do not contact
greatnonprofits-nfp/rapidpro pull request #256
Opened 2021-11-30 16:26 UTC by ihor-palii

Allow for "Do Not Contact" Times on platform
https://app.asana.com/0/1200626743215615/1201238931324195/f

2021-12-02 17:54 UTC, teehamaral requested changes

2021-12-02 17:54 UTC, teehamaral commented on templates/triggers/trigger_schedule.haml
> +            if (time < 8 || time > 21) {
I think here would be `if (time < 8 || time > 20)`, as 21h (9 PM) is the limit

2021-12-02 17:54 UTC, teehamaral commented on templates/triggers/trigger_schedule_in_batch.haml
> +          if (time < 8 || time > 21) {
I think here would be `if (time < 8 || time > 20)`, as 21h (9 PM) is the limit

2021-12-02 18:03 UTC, teehamaral commented
@ihor-palii - Could you please implement the unit tests for this feature (only for Python code)?

2021-12-06 12:31 UTC, ihor-palii commented
> @ihor-palii - Could you please implement the unit tests for this feature (only for Python code)?

I have added requested changes

2021-12-06 20:27 UTC, teehamaral approved these changes

2021-12-06 20:27 UTC, merged