added mgt command to recalculate message label count
greatnonprofits-nfp/rapidpro pull request #285
Opened 2022-03-07 02:37 UTC by musamusa

2022-03-07 14:01 UTC, teehamaral requested changes

2022-03-07 14:01 UTC, teehamaral commented on temba/msgs/management/commands/recalc_msg_label_count.py
> +        label_type = label_mapping[key]
Let's add some logs, that way we can follow what's happening with the process. E.g. something like "Recalculating for Org 1, label type S"

2022-03-07 14:47 UTC, musamusa commented on temba/msgs/management/commands/recalc_msg_label_count.py
> +            orgs = list(Org.objects.values_list("id", flat=True))
make sense

2022-03-07 22:08 UTC, teehamaral approved these changes

2022-03-08 19:06 UTC, ihor-palii approved these changes

2022-04-01 13:43 UTC, merged