Feature/chunk large sends automagically
greatnonprofits-nfp/rapidpro pull request #322
Opened 2022-10-01 07:50 UTC by musamusa

Chunk large sends automagically.
https://communityconnectlabs.atlassian.net/browse/CD-79

2022-10-03 19:12 UTC, teehamaral requested changes
Great job @musamusa, I've requested only minor changes.

2022-10-03 19:12 UTC, teehamaral commented on temba/triggers/views.py
> +            attrs={"icons": True, "placeholder": _("Optional: Select contact groups"), "searchable": True}
Groups are required but the placeholder is saying optional

2022-10-04 12:59 UTC, musamusa commented
> Great job @musamusa, I've requested only minor changes.

Thanks

2022-10-04 19:52 UTC, teehamaral approved these changes

2022-10-04 20:31 UTC, merged