Feature: OWASP Scanning
greatnonprofits-nfp/rapidpro pull request #324
Opened 2022-10-19 12:41 UTC by ihor-palii

Ticket: https://communityconnectlabs.atlassian.net/browse/CD-125

GitHub Secrets to be created:
// Email server credentials
MAIL_SERVER_ADDRESS
MAIL_SERVER_PORT
MAIL_USERNAME
MAIL_PASSWORD

// Email addresses of sender and receivers
MAIL_DEFAULT_FROM - Email address of the report sender.
MAIL_SEND_OWASP_RESULT_TO - Email addresses of receivers of the report, separated by a comma.

2022-10-19 14:30 UTC, teehamaral requested changes
Nice job! I've requested just a minor change on `push` statement. BTW - I set up the action secrets already on the repository.

2022-10-19 14:30 UTC, teehamaral commented on .github/workflows/owasp.yml
> +      - 'feature/owasp-scanning'
@ihor-palii - I guess you were using this branch on `push` statement for testing when developing the feature, but I think, per the ticket's description, it should be to dev/* and release/* as well.

2022-10-21 15:47 UTC, teehamaral approved these changes

2022-10-21 17:20 UTC, musamusa approved these changes

2022-10-21 18:02 UTC, merged