Feature/cd 181 integrate chatbot training script
greatnonprofits-nfp/rapidpro pull request #340
Opened 2023-01-02 00:28 UTC by musamusa

https://communityconnectlabs.atlassian.net/browse/CD-181

2023-01-03 16:45 UTC, teehamaral requested changes

2023-01-03 16:45 UTC, teehamaral commented on temba/classifiers/views.py
> +            languages = forms.MultipleChoiceField(
Let's rename this field to not conflict with the languages imported at the beginning of this file https://github.com/greatnonprofits-nfp/rapidpro/pull/340/files#diff-9c465579910a52b0d5bc483683fb3b2d46ae9f8ef5f4b755a50a16335f39819aR12

2023-01-03 16:45 UTC, teehamaral commented on temba/classifiers/types/dialogflow/train_bot.py
> +                self.messages["errors"].append(error_msg)
Maybe missing a 'continue' here?

2023-01-03 16:45 UTC, teehamaral commented on temba/classifiers/types/dialogflow/train_bot.py
> +    def csv_to_dict(self, language_code):
Not sure if that would be the same concept, but there's a built-in function to read the CSV as a Dict: https://docs.python.org/3/library/csv.html#csv.DictReader

2023-01-04 19:38 UTC, teehamaral approved these changes

2023-01-05 10:29 UTC, ihor-palii approved these changes

2023-01-05 15:26 UTC, merged